name: Build

on:
    push:
        branches:
            - [main, deploy]
    pull_request:
        branches:
            - [main, deploy]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Build Client
              run: |
                  cd client
                  npm install
                  npm run build

            - name: Build Server
              run: |
                  cd server
                  npm install

            - name: Build Worker
              run: |
                  cd worker
                  npm install

            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: |
                      client/build
                      server
                      worker
